# Travis CI (MIT License) configuration file for the Air-light WordPress theme.
# @link https://travis-ci.com/

# For use with the Air-light WordPress theme.
# @link https://github.com/digitoimistodude/air-light

# Ditch sudo and use containers.
# @link https://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: required
dist: xenial

# Declare project language.
# @link https://about.travis-ci.com/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
# @link https://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        - php: '7.4'
          env: SNIFF=1
        - php: 'nightly'

    allow_failures:
        - php: 'nightly'

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
before_install:
    - sudo rm -rf ~/.nvm
    - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - if [[ `node -v` != v10* ]]; then nvm install stable; fi
    - nvm install-latest-npm
    - nvm install 14.13.1
    - nvm use 14.13.1

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
    # Speed up build time by disabling Xdebug.
    - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
    # Set up temporary paths.
    - if [[ "$SNIFF" == "1" ]]; then export PHPCS_DIR=/tmp/phpcs; fi
    - if [[ "$SNIFF" == "1" ]]; then export WPCS_DIR=/tmp/wpcs; fi
    - if [[ "$SNIFF" == "1" ]]; then export PHPCOMPAT_DIR=/tmp/phpcompatibility; fi
    - if [[ "$SNIFF" == "1" ]]; then export SNIFFS_DIR=/tmp/sniffs; fi
    # Install PHP_CodeSniffer.
    - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR; fi
    # Install WordPress Coding Standards.
    - if [[ "$SNIFF" == "1" ]]; then git clone -b 2.2.1 --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $WPCS_DIR; fi
    # Set install path for WordPress Coding Standards.
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/bin/phpcs --config-set installed_paths $WPCS_DIR,$PHPCOMPAT_DIR,$SNIFFS_DIR; fi
    # After CodeSniffer install you should refresh your path.
    - if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
    # Install PHP Compatibility sniffs.
    - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $PHPCOMPAT_DIR; fi
    # Pull in the Air-light phpcs rules.
    - if [[ "$SNIFF" == "1" ]]; then wget https://raw.githubusercontent.com/digitoimistodude/air-light/master/phpcs.xml; fi
    # Install JSCS: JavaScript Code Style checker.
    # @link http://jscs.info/
    # - if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
    # Pull in the Air-light eslint rules.
    - if [[ "$SNIFF" == "1" ]]; then wget https://raw.githubusercontent.com/digitoimistodude/air-light/master/.eslintrc.js; fi
    # Install JSHint, a JavaScript Code Quality Tool.
    # @link http://jshint.com/docs/
    # - if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi
    # Pull in the WP Core jshint rules.
    # - if [[ "$SNIFF" == "1" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc; fi
    # Install eslint.
    # @link https://eslint.org/
    - if [[ "$SNIFF" == "1" ]]; then npm i -g eslint@7.22.0; fi

    # Install stylelint.
    # @link https://stylelint.io/
    - if [[ "$SNIFF" == "1" ]]; then npm i -g stylelint@14.0.1; fi
    - if [[ "$SNIFF" == "1" ]]; then npm i -g stylelint-scss@4.0.0; fi
    - if [[ "$SNIFF" == "1" ]]; then npm i -g postcss-scss@4.0.1; fi

    # Install nu-html-checker
    - if [[ "$SNIFF" == "1" ]]; then npm i -g html-validator-cli; fi

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search for PHP syntax errors.
    - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

    # Run the theme through JSHint.
    # - if [[ "$SNIFF" == "1" ]]; then jshint .; fi

    # Run the theme through JavaScript Code Style checker.
    # - if [[ "$SNIFF" == "1" ]]; then jscs .; fi

    # Run the theme through Eslint.
    - if [[ "$SNIFF" == "1" ]]; then npm i --save-dev eslint babel-eslint babel-loader babel-preset-airbnb eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks; fi
    - if [[ "$SNIFF" == "1" ]]; then npm i --save airbnb-browser-shims; fi
    - if [[ "$SNIFF" == "1" ]]; then npm link eslint; fi
    - if [[ "$SNIFF" == "1" ]]; then eslint .; fi

    # Run against WordPress Coding Standards.
    # If you use a custom ruleset, change `--standard=WordPress` to point to your ruleset file,
    # for example: `--standard=wpcs.xml`.
    # You can use any of the normal PHPCS command line arguments in the command:
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/bin/phpcs -p . --ignore=node_modules,*/css/* --standard=phpcs.xml; fi

    # Pull in the Air-light stylelint rules.
    - if [[ "$SNIFF" == "1" ]]; then wget https://raw.githubusercontent.com/digitoimistodude/air-light/master/.stylelintrc; fi

    # Run the theme through stylelint.
    - if [[ "$SNIFF" == "1" ]]; then wget https://raw.githubusercontent.com/digitoimistodude/air-light/master/package.json; fi
    - if [[ "$SNIFF" == "1" ]]; then npm i; fi
    - if [[ "$SNIFF" == "1" ]]; then npm link postcss; fi
    - if [[ "$SNIFF" == "1" ]]; then npm link stylelint; fi
    - if [[ "$SNIFF" == "1" ]]; then stylelint . --max-warnings 0 --config .stylelintrc; fi

    # Check for valid HTML
    - if [[ "$SNIFF" == "1" ]]; then html-validator "https://airwptheme.com/demo" --format=text --quiet; fi

# Receive notifications for build results.
# @link https://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
    email: true
