name: JS

on: [push, pull_request]

jobs:
  build:
    name: Test JS
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Install packages and test JS
      run: |
        rm package.json
        wget https://raw.githubusercontent.com/digitoimistodude/devpackages/master/package.json
        sed -i 's/PROJECTNAME/air-light/g' package.json
        npm i airbnb-browser-shims@^3.3.0 --save
        npm i moveto@^1.8.2 --save
        npm i reframe.js@^4.0.0 --save
        npm i
        npm i eslint@8.18.0 --save-dev
        npx eslint -c .eslintrc.js js/src/
